// WASM Worker: loads Emscripten-generated Module, runs physics, renders to OffscreenCanvas,
// and reports metrics. Assumes physics.js (generated by Emscripten) sits at /wasm/physics.js

let ctx = null;
let W = 640, H = 400;
let particles = 10000;
let speed = 1.0;
let radius = 2;
let bg = '#111111';

let Module = null;
let HEAPF32 = null;
let posXPtr = 0, posYPtr = 0;

const fpsWindow = 60;
let fpsSamples = [];
let lastFrameTime = 0;
let stepSamples = [];

self.onmessage = async (ev) => {
  const msg = ev.data;
  if (msg.type === 'init') {
    const canvas = msg.canvas;
    W = msg.width; H = msg.height;
    ctx = canvas.getContext('2d');
    await bootWasm();
    await initParticles();
    loop();
  } else if (msg.type === 'settings') {
    const restartNeeded = (particles !== msg.particles) || (radius !== msg.radius);
    particles = msg.particles;
    speed = msg.speed;
    radius = msg.radius;
    bg = msg.bg;
    if (restartNeeded) await initParticles();
  }
};

async function bootWasm() {
  // physics.js is the Emscripten output (MODULARIZE=1)
  importScripts('/wasm/physics.js');
  // physics.js exposes a factory function; the global name depends on your -o target.
  // Emscripten sets global 'Module' when not using MODULARIZE=1, so we require MODULARIZE=1.
  // When using MODULARIZE=1, the factory is the exported function name (e.g., 'Module').
  // By default, emcc -s MODULARIZE=1 -o physics.js exports 'Module' factory.
  // eslint-disable-next-line no-undef
  Module = await ModuleFactory(); // see build instructions: we’ll name the factory ModuleFactory

  HEAPF32 = Module.HEAPF32;
}

// Re-init particles in WASM
async function initParticles() {
  // Bind C functions
  const init_particles = Module.cwrap('init_particles', null, ['number', 'number', 'number', 'number', 'number']);
  const get_posX_ptr = Module.cwrap('get_posX_ptr', 'number', []);
  const get_posY_ptr = Module.cwrap('get_posY_ptr', 'number', []);

  init_particles(particles, W, H, speed, radius);
  posXPtr = get_posX_ptr();
  posYPtr = get_posY_ptr();
}

function physicsStep(dt) {
  const start = performance.now();
  const stepFn = Module.cwrap('step', null, ['number']);
  stepFn(dt);
  const end = performance.now();
  stepSamples.push(end - start);
  if (stepSamples.length > fpsWindow) stepSamples.shift();
}

function render() {
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);

  const r = radius;
  const posX = HEAPF32.subarray(posXPtr >> 2, (posXPtr >> 2) + particles);
  const posY = HEAPF32.subarray(posYPtr >> 2, (posYPtr >> 2) + particles);

  ctx.fillStyle = '#ffd166';
  for (let i = 0; i < particles; i++) {
    ctx.fillRect(posX[i] - r, posY[i] - r, r * 2, r * 2);
  }
}

function loop() {
  const now = performance.now();
  if (lastFrameTime === 0) lastFrameTime = now;
  const dt = Math.min((now - lastFrameTime) / 1000, 0.1);
  lastFrameTime = now;

  physicsStep(dt);
  render();

  const fps = 1000 / (dt * 1000);
  fpsSamples.push(fps);
  if (fpsSamples.length > fpsWindow) fpsSamples.shift();

  const memBytes = Module.wasmMemory?.buffer?.byteLength || Module.HEAP8?.length || 0;
  const memStr = `${(memBytes / (1024 * 1024)).toFixed(1)} MB`;

  postMessage({
    type: 'metrics',
    fps: {
      current: fps,
      avg: average(fpsSamples),
      min: Math.min(...fpsSamples),
      max: Math.max(...fpsSamples),
    },
    step: {
      avg: average(stepSamples),
    },
    memory: {
      wasm: memStr,
    },
    config: {
      particles,
      speed,
      radius,
    }
  });

  setTimeout(loop, 1000 / 60);
}

function average(arr) {
  if (!arr.length) return 0;
  let s = 0;
  for (let v of arr) s += v;
  return s / arr.length;
}

// ---- Emscripten factory name mapping ----
// If you compile with: emcc ... -s MODULARIZE=1 -o wasm/physics.js
// Emscripten generates a factory function with the name set in -s EXPORT_NAME.
// We’ll set EXPORT_NAME=ModuleFactory in the build command so we can call ModuleFactory() here.
